### ISSUE TITLE
Support for MSVC and Windows

### ISSUE THREAD

**Issue by Neko-Box-Coder** [Neko-Box-Coder/ssGUI#3]
[Previous discussions](https://github.com/Neko-Box-Coder/ssGUI/discussions/2) about setting up for MSVC

### Goals:
- Greater support and documentation so it is easy to setup for MSVC and Windows

**Comment by Neko-Box-Coder** [comment]
@andreyminea
For the crash, if you add 
`# include "ssGUI/DebugAndBuild/ssGUIDebugInit.hpp"` and
`#include "ssGUI/DebugAndBuild/ssGUIBuildAndDebugConfig.hpp"`

Then modify `ssGUIDebugInit.hpp` 
`#define USE_DEBUG 0` to `#define USE_DEBUG 1`.

Then it should print the call stack on where it crashed (hopefully)

**Comment by andreyminea** [comment]
Please add a separate branch for pull-request

**Comment by andreyminea** [comment]
> For the crash, if you add
# include "ssGUI/DebugAndBuild/ssGUIDebugInit.hpp" and
#include "ssGUI/DebugAndBuild/ssGUIBuildAndDebugConfig.hpp"
Then modify ssGUIDebugInit.hpp
#define USE_DEBUG 0 to #define USE_DEBUG 1.
Then it should print the call stack on where it crashed (hopefully)
But first which example are you running?

For some reason it these macros result in a compile error

**Comment by Neko-Box-Coder** [comment]
I have just created an MSVC branch. 
I will check out your branch today and see if there's anything wrong.

**Comment by Neko-Box-Coder** [comment]
Quick update, I am currently trying to get it working on MSVC (Both via CMake or just manually including everything)
Documentations and fixes will be done hopefully at some point.

**Comment by Neko-Box-Coder** [comment]
The new release should work on MSVC now on v0.93
